# Install the configuration using `pre-commit install`
# Manually execute the configuration using `pre-commit run` (include `--all-files` to run on all files instead of only on staged files)

repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.5
    hooks:
      - id: ruff
        name: Ruff Linter
        args: [--fix]
        pass_filenames: true
        language_version: python3
        types: [python]

      - id: ruff-format
        name: Ruff Formatter
        args: []
        pass_filenames: true
        language_version: python3
        types: [python]
