# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

select = [
 "B",   #bugbear
 "D",   #pydocstyle
 "BLE", #flake8-blind-except
 "C4",  #flake8-comprehensions
 "ERA", #eradicate
 "E",   #pycodestyle
 "F",   #Pyflakes
 "N",   #pep8-naming
 "I",   #isort
 "PL",  #Pylint
 "UP",  #pyupgrade
 "SIM", #flake8-simplify
 "TCH", #flake8-type-checking
 "PTH", #flake8-use-pathlib
 "TID", #flake8-tidy-imports
 "PT",  #flake8-pytest-style
 "W",   #pycodestyle
 "RUF", #ruff
 ]
show-fixes = true
pydocstyle.convention = "google"

# Same as Black.
line-length = 140
indent-width = 4

# Assume Python 3.11
target-version = "py311"

[lint]
ignore = ["D211", "D213"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
# Ignore `E402` (import violations) in all `__init__.py` files, and in select subdirectories.
"__init__.py" = ["E402", "F401"]
"**/{tests,docs,tools}/*" = ["E402"]

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
